### ISSUE TITLE
loss问题

### ISSUE THREAD

**Issue by GISer-WB** [cds-mipt/deeplabv3plus#1]
您好，我想问一下，为什么按照您的说明进行loss的设置，预测结果还是一片黑？能帮助我一下吗？感谢。

**Comment by adeshkin** [comment]
in English, please

**Comment by GISer-WB** [comment]
According to your instructions, the loss is set, and the predicted result is still black?Can you give me a hand?Thank you.

**Comment by adeshkin** [comment]
Have you tried to run without loss weights for your task? I've solved specific task, so used them. Try to run according official source https://github.com/tensorflow/models/tree/master/research/deeplab . If you'll have questions, I'd be happy to answer them.
